#+TITLE: Teorias Probabilidad y Estadística 

* Introducción Toma Decisiones
** Introducción
La Estadistica y el Metodo Cientifico nos proveen un conjuto de  
principios y procedimientos para obtener y resumir la informacion  
para la *Toma de Decisiones*.

El metodo Cientifico comprende los siguientes pasos:
- Formular Teorias
- Recoleccion de datos
- Resumen y Analisis de Datos
- Interpretacion de los resultados
** Decisiones
- Simples 
Puedo cruzar la calle en esta interseccion?
- Complejas
Supongamos que quiero comprar un nuevo  
auto 0KM y decido hacerlo con la General Motors. La respuesta  
a las siguientes preguntas puede influir sobre la decision:  
Distintos modelos producidos en el corriente ano, que modelo es  
mas eficiente en cuanto a Km recorridos por litro de combustible,  
en precio ? 
** Lenguaje de la estadistica en la toma de Decisiones
Esta nueva terminología involucra frases, símbolos y definiciones especiales. El  
significado de una palabra es el lenguaje corriente puede ser diferente de cómo esa  
palabra está definida en el contexto de la Estadística. En esta Sección discutiremos la  
terminología estadística en el contexto del proceso de tomar decisiones. Hay muchas  
componentes en este proceso; incluye teorías, datos, una medida de “likeliness” y la  
posibilidad de errores.  
*** El ensayo de las Teorias
* La Estadística Descriptiva
La *Estadistica* es la ciencia de recolectar, analizar y 
sacar conclusiones a partir de un conjunto de datos.
En este proceso se pueden diferenciar dos partes:
- _Estadistica descriptiva:_ Organizar y resumir la información
en tablas, gráficos y medidas resumen.
- _Estadística inferencial:_ Sacar conclusiones o tomar decisiones.

Le llamaremos *población* al conjunto de objetos acerca del cual 
se desea obtener información. Y *muestra* es un subconjunto de la
población y será lo que se estudiará para sacar conclusiones. Estas
muestras deben ser respresentativas para obtener buenas conclusiones.

Una *variable* es una característica cuyo valor, o dato, puede cambiar de un 
objeto a otro. Los conjuntos de datos se diferencian según la cantidad
de variables observables, estos pueden ser univariado, bivariado o multivariado

Las medidas resumen que se obtienen de una población se denominan
*parámetro* y los que se obtienen a partir de una muestra se llama *estadistica*.

** Tipos de variables
_Categórica:_  Cada observación pertenece a un conjunto de categorías. La característica fundamental 
a describir es el número relativo de observaciones en las distintas categorías.
_Cuatitativa:_ Cada observación toma valores numéricos que representan diferentes magnitudes.
Con este tipo de variables se calculan las medidas resumen con excepción de las que no representan 
una cantidad o magnitud, ejemplo: código de área. Las característica a describir son el centro
y la variabilidad o dispersión de los datos.
Estas se dividen en 
_Discretas:_ Cada valor que toma pertenece a un conjunto discreto, como los número enteros.
_Continua:_ Cada valor que toma pertenece a un conjunto continuo, como un intervalo.


** Analisis decriptivo para variables categóricas
_Tablas de frecuencias:_ Como cada observación cae en una categoría, 
podemos usar proporciones o porcentajes (frecuencias relativas) para resumir el número de observaciones.
La proporcion es la cantidad de observaciones de esa categoria sobre el total de las observaciones. El
porcentaje es la proporción multiplicado por 100.

| Categoría | Frecuencia | Frecuencia Relativa | Frecuencia Relativa Porcentual|
|-----------|------------|---------------------|-------------------------------|
| Si        | 51         | 0.51                | 51%                           |
| No        | 49         | 0.49                | 49%                           |
| Total     | 100        | 1.00                | 100%                          |

_Gráfico de torta:_  Consiste en un círculo con sectores, donde cada sector es una categoria.
El tamaño del sector es proporcional a su frecuencia relativa. Se utilizan cuando hay pocas 
categorías.
#+BEGIN_SRC R :exports results :file img/grafico-torta.png
library(ggplot2)

# Datos
datos <- data.frame(
Categoria = c("Si", "No"),
Frecuencia = c(51, 49)
)

# Crear el gráfico de torta
ggplot(datos, aes(x = "", y = Frecuencia, fill = Categoria)) +
geom_bar(stat = "identity", width = 1, color = "white") +
coord_polar("y", start = 0) +
theme_void() +
theme(legend.position="bottom") +
labs(title = "Gráfico de Torta", fill = "Categoría", y = NULL)
#+END_SRC
* TODO Probabilidad
* TODO Variables Aleatorias y Distribuciones
* TODO Variables Aleatorias Continuas
* TODO Variables Aleatorias de Dim >= 2
* TODO Proceso de Poisson, Bernulli y Cadena de Markov
